//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelEDM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OurMoneyDbEntities : DbContext
    {
        public OurMoneyDbEntities()
            : base("name=OurMoneyDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dictionaries> Dictionaries { get; set; }
        public virtual DbSet<Entities> Entities { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<Images> Images { get; set; }
    }
}
