//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelEDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictionaries
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dictionaries()
        {
            this.Events = new HashSet<Events>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> Rate { get; set; }
        public string Comment { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> PrevId { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> ImageId { get; set; }
        public Nullable<bool> Hidden { get; set; }
    
        public virtual Entities Entities { get; set; }
        public virtual Images Images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Events> Events { get; set; }
    }
}
