//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelEDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        public int Id { get; set; }
        public int OperationType { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public System.DateTime Date { get; set; }
        public string Comment { get; set; }
        public int AccountId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> MarketId { get; set; }
        public Nullable<int> DebtId { get; set; }
    
        public virtual Dictionaries Dictionaries { get; set; }
    }
}
