//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurMoneyWpf.DataProvider.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictionary
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> Rate { get; set; }
        public string Comment { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int EntityType { get; set; }
        public Nullable<int> ImageId { get; set; }
        public Nullable<bool> Hidden { get; set; }
    }
}
