//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurMoneyWpf.DataProvider.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> MarketId { get; set; }
        public int AccountId { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public decimal Amount { get; set; }
    }
}
