//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurMoneyWpf.DataProvider.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OurMoneyDbContext : DbContext
    {
        //public OurMoneyDbContext()
        //    : base("name=OurMoneyDbContext")
        //{
        //}
        public OurMoneyDbContext()
            : base("name=SQLiteConnection")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
 //           throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dictionary> Dictionaries { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
    }
}
